inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
    NewCops: enable
    Exclude:
      - db/**/*.rb
      - "config/initializers/*"
      - "vendor/**/*"
      - "bin/*"

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Style/FrozenStringLiteralComment:
  Enabled: false