version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0
  node: circleci/node@5.0.3

commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.4-node
    steps:
      - setup

  test:
    docker:
      - image: cimg/postgres:14.4
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: recorda_me_test
    environment:
        RAILS_ENV: test
        DATABASE_HOST: 127.0.0.1
        BUNDLE_JOBS: "4"
        BUNDLE_RETRY: "3"
    steps:
      - setup
      - run:
          name: Wait for DB
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
      - run:
          name: Database setup
          command: 'bundle exec rails db:schema:load --trace'
      - ruby/rspec-test:
          include: spec/**/*_spec.rb\

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build