version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2


commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.4-node-browsers
    steps:
      - setup

  test:
    docker:
      - image: circleci/ruby:3.0.3-node-browsers
      # DBの設定
      - image: circleci/postgres:11.14
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: recorda_me_test
    environment:
      RAILS_ENV: test
      DATABASE_HOST: 127.0.0.1
      BUNDLE_JOBS: "4"
      BUNDLE_RETRY: "3"
    steps:
      - setup
      - run:
          name: Migrating DB
          command: rails db:migrate
      - run:
          name: Database setup
          command: budle exec rails db:schema:load --trace
      - run:
          name: Rspec Test
          command: bundle exe rspec


workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build
