version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0
  node: circleci/node@5.0.3
  browser-tools: circleci/browser-tools@1.4.0

commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.4-browsers
    steps:
      - setup

  checking:
    docker:
      - image: 'cimg/ruby:3.0.4'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop

  test:
    docker:
      - image: cimg/ruby:3.0.4-browsers
      - image: cimg/postgres:14.4
        environment:
          POSTGRES_PASSWORD: postgres
        name: postgres_db
    environment:
        RAILS_ENV: test
        DATABASE_HOST: postgres_db
        BUNDLE_JOBS: "4"
        BUNDLE_RETRY: "3"
        CIRCLECI: circleci
    steps:
      - setup
      - run:
          name: Wait for DB
          command: 'dockerize -wait tcp://postgres_db:5432 -timeout 1m'
      - run:
          name: Database setup
          command: bundle exec rails db:create && bundle exec rails db:migrate
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - ruby/rspec-test:
          include: spec/**/*_spec.rb

  deploy:
      docker:
        - image: cimg/ruby:3.0.4-browsers
      steps:
      - checkout
      - ruby/install-deps
      - add_ssh_keys:
          fingerprints:
            - "a1:a6:dc:87:b3:12:12:82:23:00:33:09:0d:ba:c8:2b"
      - deploy:
          name: Capistrano deploy
          command: bundle exec cap production deploy


workflows:
  build_test_and_deploy:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
      - deploy
          # requires:
          #   - test
          # filters:
          #     branches:
          #       only: main
